### ISSUE TITLE
error

### ISSUE THREAD

**Issue by uru8** [hawkfalcon/Stardew-Mods#36] opened 2024-04-19 17:47 UTC
https://smapi.io/log/1fe3eb0a0264477488d693db5071ef1e
i don‘t know what‘s that mean

**Comment by uru8** [comment] 2024-04-19 17:51
A large number of errors will cause my game to become stuck，It may have something to do with the fact that I have a lot of junimo huts in the sve-Grampleton Fields, but I still get errors on my farm

**Comment by TheSeaMoon4** [comment] 2024-04-19 18:48
It's exactly because you have a large amount in the SVE Grampleton Fields, this mod isn't meant to be used anywhere else than the farm you start with (It works on modded farm that replace the normal farms but not those that are added on top of the normal farm)

**Comment by hawkfalcon** [comment] 2024-05-02 05:17
Dupe of #34

**Closed by hawkfalcon** 2024-05-02 05:17 UTC
